### ISSUE TITLE
Using external jsx instead of inline one

### ISSUE THREAD

**Issue by varadig** [massiveinteractive/haxe-react#79] opened 2017-09-29 09:39 UTC
I wanted to use external jsx for instead of inline, with compiletime macro:
```

class Main {
    public static function main() {
        AppRegistry.registerComponent('TestReactNative', function() return App);

    }
}
@:expose('App')
class App extends ReactComponent{
    function new(props) {

        super(props);

        state = {
            scene: 0
        }
    }


    override function render() {
        function goto(i) setState({scene: i});
        return switch state.scene {
            default:
                jsx(CompileTime.readFile("jsx/Home.jsx"));
        }
    }
}
```
Home.jsx:
```
<WebView
    source={{uri: 'https://github.com/facebook/react-native'}}
    style={{marginTop: 20}}
>

</WebView>

```

but  I got this error when compile:

```
/usr/local/lib/haxe/std/haxe/macro/ExprTools.hx:289: characters 11-16 : Unsupported expression: { expr => ECall({ expr => EField({ expr => EConst(CIdent(CompileTime)), pos => #pos(src/Main.hx:35: characters 20-31) },interpolateFile), pos => #pos(src/Main.hx:35: characters 20-47) },[{ expr => EConst(CString(jsx/Home.jsx)), pos => #pos(src/Main.hx:35: characters 48-62) }]), pos => #pos(src/Main.hx:35: characters 20-63) }
/Volumes/Work/develop/hx/libs/react/git/src/lib/react/ReactMacro.hx:27: characters 19-43 : Called from
src/Main.hx:35: characters 16-64 : Called from
```

How can I use external jsx with RNhaxe, if I can?

thanks

**Comment by elsassph** [comment] 2017-09-29 11:32
It's a good idea, but the JSX macro runs before your `readFile`.

I encourage you to look into forking haxe-react and patching the JSX macro to support something native like:
```haxe
    override function render() {
        function goto(i) setState({scene: i});
        return switch state.scene {
            default:
                jsx("./jsx/Home.jsx");
        }
    }
```

**Comment by elsassph** [comment] 2017-10-03 13:30
Duplicate of issue #1

**Closed as completed by elsassph** 2017-10-03 13:30 UTC
Labels: enhancement
